version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smile_classifier_container_final
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - YSDTP_B4_AI_30179
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_NAME: smiledatabase
      DATABASE_PASSWORD: root
    command: ["wait-for-it", "db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]

  db:
    image: mysql:8.0.20
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smiledatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - YSDTP_B4_AI_30179
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  YSDTP_B4_AI_30179: